version: "3"

services:
  app:
    build: .
    container_name: integration-node
    ports:
      - 8050:8050
    volumes:
      - .:/usr/app
      - ./docker:/root/.ssh
    command: ["npm", "run", "serve"]
